title:            gig&#58; Dev Local
description:      Full-stack development that puts experience first.
logo:             site-logo.png
disqus_shortname:
search:           false

# Change url to your domain. Leave localhost server or blank when working locally.
# You don't need to specify the protocol if you want it available on http and https. Example: //localhost:4000

url:             //greenfieldinnovation.com # !!! use only in permalinks !!!
# detach:  false
port:    4900
#host:    0.0.0.0
#baseurl: "" # does not include hostname

corp:
  llc:            Expinnovate LLC
  dba:            Greenfield Innovation Group


# Owner/author information
owner:
  name:           Monte Hayward
  #TODO: avatar:         bio-photo.jpg
  email:          monte@montehayward.com
  # Social networking links used in footer. Update and remove as you like.
  angelco:  gig-greenfield-innovation-group
  twitter:  monte_hayward
  facebook: greenfieldinnovation
  github:   
  stackexchange:
  linkedin:         monte
  instagram:
  flickr:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:  #TODO:

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-48976618-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

#  Defaults appear not to work as described.
#  http://jekyllrb.com/docs/configuration/#frontmatter-defaults
# defaults:
#  -
#    scope:
#      path: ""
#      type: "posts"
#    values:
#      tags: [responsive, software development service, dev-on-demand, contract, hourly, retainer, senior user experience engineer]
#      layout: "page"
      # image:
      #   background: summer_field_1920x1170_progressive.jpg
      #   credit: Wallpaperstock.net
      #   creditlink: 


# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Services
    url: /services/
  - title: About
    url:  /about/
  - title: Contact
    url: /contact/
  - title: ""
    url: /examples/
#  - title: Blog
#    url: /blog/

source:      ./.tmp/3thin
destination: ./_site

timezone:    America/Chicago      # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
future:      true
highlighter: pygments
markdown:    kramdown
encoding:    utf-8
permalink:   /:categories/:title/ # https://github.com/mojombo/jekyll/wiki/Permalinks
relative_permalinks: false

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: [
  "config.rb", "Rakefile", "Rakefile.rb", "tmp", "Gemfile", "Capfile", "Gemfile.lock",
  "Gruntfile.js", "package.json", "node_modules",
  "README.md", "LICENSE",
  "config", "log", "lib", 
  "test", 
  "less", 
 # 'css',
#  'sass',
#  'js',
  'coffee',
  'env',
  'tmp',
  "spec",
  'requirements.txt',
  "*.sublime-project", "*.sublime-workspace"
]

# original theme exclude: ["lib", "config.rb", "Gemfile", "Capfile", "README.md", "LICENSE", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]


